### ISSUE TITLE
Masked blocks in TSS are assigned 0 instead of nodata value

### ISSUE THREAD

**Issue by ernstste** [davidfrantz/force#234]
Maybe related to #26:

When producing TSS with masks in v3.7.8, there are some masked areas that are assigned 0 instead of the nodata value. The issue does not occur when using v3.7.7. We also didn't observe this when Landsat was processed for the same 30x30km tile - same block size (3000) but 30m res instead of 10m.

![sdf](https://user-images.githubusercontent.com/15325433/192568320-a6ebbb9b-1cfc-4874-89cc-5b26e35fe312.png)

**Comment by davidfrantz** [comment]
I wonder what I changed... I guess I will need to implement the CSO fix in each sub-module

**Comment by davidfrantz** [comment]
Hey @ernstste, did https://github.com/davidfrantz/force/issues/26 ever work? I just made a small test, and it doesn't work for TSA and CSO.

I tried to pin down the issue, and problem is, that data for this chunk are neither read, computed, nor written.
I guess that the GeoTiff is sparse, though I do not understand yet why this worked in the past.

**Comment by davidfrantz** [comment]
Damn

**Comment by davidfrantz** [comment]
This bug was introduced when implementing the custom GDAL options where you can define your own output format and choose your own driver.

Not every driver supports "creating" a dataset, some need to create by copying an existing one. This can be an in-memory dataset, however. And to be most flexible and simplify the code, I followed that strategy for all drivers, i.e.

1) create dataset in-memory
2) copy dataset to disk

Apparently, this does not work with sparse files somehow... ugh. 

I guess I will need to check if the driver can create files, and then work around this by either directly creating or create/copying only if needed.

**Comment by ernstste** [comment]
Ouch. Custom GDAL options come back to bite you again.

I'm pretty sure #26 did work back then. I tried it right after you implemented the fix and the results looked ok.

**Comment by davidfrantz** [comment]
It might be, that the problem does not consistently surface - you also mentioned that you did not see that issue with Landsat data.

**Comment by davidfrantz** [comment]
I worked on a fix: https://github.com/davidfrantz/force/commit/d9759f64204a563723ec39f63970928267a77751

I think it solves this issue. 

The only thing to mention (and I believe this already did not work before) is that I could not make ``create/copy drivers`` work for block-output (like in HLPS). If full files are written, it works, however (like the OVV images in L2PS).

**Comment by spengler-iamo** [comment]
Hi David,
I am experiencing that behaviour using FORCE v. 3.10.04. I am assuming it is related to the chunk size parameter introduced in v 3.9. The tile size of my LEVEL2 data is 30 km in EPSG:3035. I tried chunk sizes 30000x30000 and 1000x1000. 
But I'm not sure that is the root cause. 

<img width="1548" height="1059" alt="Image" src="https://github.com/user-attachments/assets/bbf68e05-7264-45b7-912f-80f90a80a25a" />

<img width="1166" height="1164" alt="Image" src="https://github.com/user-attachments/assets/4d941320-5bff-4326-a289-19496c59188b" />

**Comment by davidfrantz** [comment]
Hi @spengler-iamo ,

can you please open a new issue, refer to this one, and provide more information on your parameterization?
