### ISSUE TITLE
force-higher-level: wrong sensor names in stacked output

### ISSUE THREAD

**Issue by jakimowb** [davidfrantz/force#25]
force-higher-level allows to create a stack of a spectral index, e.g. NBR or NDVI, with number of bands = number of level2 input observations.

Each band of the index values stack provides metadata information in FORCE domain, that can be accesses by GDAL as followed:

```
b = ds.GetRasterBand(1)
b.GetMetadata('FORCE')
{'Date': '2018-02-27T00:00:00.0Z', 'Domain': '20180227', 'Scale': '10000.000', 'Sensor': 'LND08', 'Wavelength': '2018.156', 'Wavelength_unit': 'decimal year'}
b = ds.GetRasterBand(2)
b.GetMetadata('FORCE')
{'Date': '2018-04-17T00:00:00.0Z', 'Domain': '20180417', 'Scale': '10000.000', 'Sensor': 'LND08', 'Wavelength': '2018.290', 'Wavelength_unit': 'decimal year'}
```

Problem: in case of multiple sensors the `Sensor` metadata value is always the value of the sensor from the 1st time series observation. In the upper example (see attached zip) the L2 observation for `Date`:2018-04-17 is from Sensor `SEN2B` instead of `LND08`.
[bugstamp.zip](https://github.com/davidfrantz/force/files/4729781/bugstamp.zip)

**Comment by davidfrantz** [comment]
Yes, this is a leftover from initializing the internal struct.

This is now fixed with https://github.com/davidfrantz/force/commit/853857d85c5296f36a07f1c703cdb093db01db57 in the develop branch in the TSA submodule.

Note that only TSS and RMS will have individual sensor names. All other products, e.g. STM or TSI will have "BLEND" as sensor name.
