### ISSUE TITLE
lance-modis expiring all app keys in favor of using tokens

### ISSUE THREAD

**Issue by vincentschut** [davidfrantz/force#89]
Considering this message I received a few days ago from Lance-modis:

> Dear LANCE-MODIS Users:

> 
> Starting 6/1/2021 we will be expiring all app keys in favor of using tokens. If you authenticate via the “Authorization: Bearer <app key>” HTTPS header and the app key you provide is formatted as XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX then the app key will stop working starting 6/1/2021. To prevent disruption in your access to data please generate a new token. You can find instructions to generate a new token at https://ladsweb.modaps.eosdis.nasa.gov/tools-and-services/data-download-scripts/#tokens
> 
> 
> Regards,
> lance-modis Users Support

I think force-lut-modis will break because that is still using the deprecated "app key" instead of the newer "token".

**Comment by davidfrantz** [comment]
...every year another authentification, sigh.

However, the usage of token and app key seems to be the same. I have this format string: 
``snprintf(auth, size, "Authorization: Bearer %s", key);`` 
``key`` is coming from the ``.laads`` file.

If I am not missing something, this is the same usage as described on the page you have provided:
``Authorization: Bearer MY_TOKEN``

I assume that it will simply work if you put a token instead of app key into the ``.laads`` file.

Cheers,
David

**Comment by vincentschut** [comment]
Ah, sorry, I missed that. I'll test it with a new token to see if it works, and if not, I'll report back here.

**Comment by davidfrantz** [comment]
Okay, I close this issue then. Please open a new one if there will be a problem!
